apiVersion: v1
kind: ConfigMap
metadata:
  name: kasa-config
  namespace: kasa-flask-server
data:
  HS300_IP: "10.0.0.40"
  KP125M_IPS: |
    - 10.0.0.146
    - 10.0.0.100
    - 10.0.0.212
    - 10.0.0.98
    - 10.0.0.135
    - 10.0.0.114
