apiVersion: v1
kind: ConfigMap
metadata:
  name: kasa-config
  namespace: kasa-flask-server
data:
  HS300_IP: "10.20.0.40"
  KP125M_IPS: |
    - 10.20.0.100
    - 10.20.0.98
    - 10.20.0.134
    - 10.20.0.115
    - 10.20.0.146
