apiVersion: v1
kind: ConfigMap
metadata:
  name: kasa-config
  namespace: kasa-flask-server
data:
  HS300_IP: "195.168.1.226"
  KP125M_IPS: |
    - 195.168.1.219
    - 195.168.1.127
    - 195.168.1.129
    - 195.168.1.186
    - 195.168.1.110
    - 195.168.1.193
