apiVersion: v1
kind: ConfigMap
metadata:
  name: kasa-config
  namespace: kasa-flask-server
data:
  HS300_IP: "10.195.1.226"
  KP125M_IPS: |
    - 10.195.1.127
    - 10.195.1.129
    - 10.195.1.186
    - 10.195.1.109
