apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-deployment
  namespace: transmission
  labels:
    app: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: transmission-pod
          image: nathannnli/mytransmission:v2
          imagePullPolicy: Always
          volumeMounts:
            - name: transmission-config
              mountPath: /config
            - name: transmission-downloads
              mountPath: /downloads
          ports:
            - containerPort: 9091      # Web UI
            - containerPort: 51413     # Torrent traffic port
      volumes:
        - name: transmission-config
          configMap:
            name: transmission-settings
        - name: transmission-downloads
          hostPath:
            path: /home/nathan/teamos/torrent-complete
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: transmission-nodeport
  namespace: transmission
spec:
  selector:
    app: transmission
  ports:
    - name: transmission-nodeport
      protocol: TCP
      port: 9091
      targetPort: 9091
      nodePort: 31091
  type: NodePort