apiVersion: v1
kind: Pod
metadata:
  name: transmission
  namespace: transmission
spec:
  containers:
  - name: transmission
    image: nathannnli/mytransmission:v1
    ports:
    - containerPort: 9091      # Web UI
    - containerPort: 51413     # Torrent traffic port
    volumeMounts:
    - name: downloads
      mountPath: /downloads    # This path inside container should be configured as download dir
    - name: config
      mountPath: /config       # Transmission config directory
  volumes:
  - name: downloads
    hostPath:
      path: /home/nathan/teamos/torrent-complete
      type: Directory
  - name: config
    emptyDir: {}  # Or set up separate persistent config storage
